export enum CowColorPattern {
  BLACK_WHITE,
  BROWN_WHITE,
  SOLID_BROWN,
  SOLID_BLACK,
}

export const REAL_MINUTES_PER_GAME_DAY = 15;
export const GAME_MINUTES_IN_DAY = 24 * 60; // 1440
export const REAL_MS_IN_GAME_MINUTE =
  (REAL_MINUTES_PER_GAME_DAY * 60 * 1000) / GAME_MINUTES_IN_DAY;
